SilverStripe\Control\Director:
    rules:
        'graphql': '%$SilverStripe\GraphQL\Controller.default'

SilverStripe\GraphQL\Manager:
    schemas:
        default:
            types:
                drink: 'SilverStripe\StereoNightclub\GraphQL\DrinkTypeCreator'
                ingredient: 'SilverStripe\StereoNightclub\GraphQL\IngredientTypeCreator'
                csrfToken: 'SilverStripe\StereoNightclub\GraphQL\CsrfTokenTypeCreator'
            queries:
                readDrink: 'SilverStripe\StereoNightclub\GraphQL\ReadDrinkQueryCreator'
                readDrinks: 'SilverStripe\StereoNightclub\GraphQL\ReadDrinksQueryCreator'
                readIngredients: 'SilverStripe\StereoNightclub\GraphQL\ReadIngredientsQueryCreator'
                readCsrfToken: 'SilverStripe\StereoNightclub\GraphQL\ReadCsrfTokenQueryCreator'

SilverStripe\GraphQL\Controller:
    cors:
        Enabled: true
        Allow-Origin: 
            - 'http://localhost:3000'
            - 'http://localhost:8888'
            - 'https://stereo-nightclub-nuxt-client.herokuapp.com'
        Allow-Headers: 'Authorization, Content-Type, X-CSRF-TOKEN'
        Allow-Methods: 'GET, POST, OPTIONS'
        Allow-Credentials: 'true'