SilverStripe\Control\Director:
    rules:
        "graphql": "%$SilverStripe\GraphQL\Controller.default"

SilverStripe\GraphQL\Manager:
    schemas:
        default:
            types:
                drink: "SilverStripe\StereoNightclub\GraphQL\DrinkTypeCreator"
                ingredient: "SilverStripe\StereoNightclub\GraphQL\IngredientTypeCreator"
            queries:
                readDrink: "SilverStripe\StereoNightclub\GraphQL\ReadDrinkQueryCreator"
                readDrinks: "SilverStripe\StereoNightclub\GraphQL\ReadDrinksQueryCreator"
                readIngredients: "SilverStripe\StereoNightclub\GraphQL\ReadIngredientsQueryCreator"

SilverStripe\GraphQL\Controller:
    cors:
        Enabled: true
        Allow-Origin: "*"
        Allow-Headers: "Authorization, Content-Type"
        Allow-Methods: "GET, POST, OPTIONS"
        Allow-Credentials: "true"
        Max-Age: 600 # 600 seconds = 10 minutes.
